import pytest
from app.core.config import settings
from app.services.ai_service import AIService
from app.schemas.chat import ChatMessage

pytestmark = pytest.mark.anyio

@pytest.mark.skipif(not settings.ai_is_real, reason="Real AI API key not configured")
class TestRealModelRuntime:
    async def _get_response(self, prompt: str) -> str:
        service = AIService()
        messages = [ChatMessage(role="user", content=prompt)]
        chunks = []
        async for chunk in service.stream_chat(messages=messages, model_alias="intelligence", temperature=0.3):
            chunks.append(chunk)
        return "".join(chunks).strip()

    def _assert_no_mock_phrases(self, text: str, prompt: str):
        # The response must not be empty
        assert text, "Response is empty"
        # The response must not be an echo of the mock server
        assert "I received your message" not in text, "Response is the mock server echo response"
        assert "How can I assist you further?" not in text, "Response contains mock helper response"
        # The response should not just be the user's prompt echoed back
        assert text != prompt, "Response is just an echo of the prompt"

    async def test_natural_greeting(self):
        prompt = "hi"
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        # Should be a natural greeting, e.g. containing "hello", "hi", "how can I help" (as generated by LLM, not verbatim mock)
        assert len(response) > 0

    async def test_what_is_python(self):
        prompt = "What is Python?"
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        # Verify it contains relevant words for Python explanation
        assert any(word in response.lower() for word in ["programming", "language", "guido", "interpreted"]), "Response does not explain Python"

    async def test_two_plus_two(self):
        prompt = "2 + 2"
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        # Should contain the number 4
        assert "4" in response, "Response does not contain 4"

    async def test_prime_program(self):
        prompt = "Write a Python program to check whether a number is prime."
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        
        # Verify the response contains expected programming concepts
        lower_response = response.lower()
        assert "def " in response, "Response does not contain 'def'"
        assert "prime" in lower_response, "Response does not contain 'prime'"
        assert "for " in response or "while " in response, "Response does not contain loop ('for' or 'while')"
        assert "%" in response or "modulo" in lower_response, "Response does not contain modulo operator or concept"

    async def test_recursion_explanation(self):
        prompt = "Explain recursion in simple words."
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        # Verify recursion keywords
        lower_response = response.lower()
        assert any(word in lower_response for word in ["recursion", "recursive", "itself", "calls", "base case"]), "Response does not explain recursion"

    async def test_explain_machine_learning(self):
        prompt = "Explain machine learning in simple terms."
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        lower_response = response.lower()
        assert any(word in lower_response for word in ["learn", "patterns", "data", "machine learning"]), "Response does not explain machine learning"

    async def test_capital_of_india(self):
        prompt = "What is the capital of India?"
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        assert "New Delhi" in response or "new delhi" in response.lower(), "Response does not state capital of India"

    async def test_solve_math(self):
        prompt = "Solve 25 * 48."
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        assert "1200" in response, "Response does not contain 1200"

    async def test_explain_code_binary_search(self):
        prompt = "Explain this code:\ndef search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target: return mid\n        elif arr[mid] < target: low = mid + 1\n        else: high = mid - 1\n    return -1"
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        lower_response = response.lower()
        assert "binary search" in lower_response or "binary" in lower_response, "Response does not explain binary search code"

    async def test_java_binary_search(self):
        prompt = "Write Java code for binary search."
        response = await self._get_response(prompt)
        self._assert_no_mock_phrases(response, prompt)
        assert "class " in response or "public " in response, "Response does not contain Java structure"
        assert "binarySearch" in response or "binarysearch" in response.lower(), "Response does not implement binary search"
